//-------------------------------------------------------------
// CS 7240 Principles of scalable data management
// https://northeastern-datalab.github.io/cs7240/
// Wolfgang Gatterbauer
//-------------------------------------------------------------

.decl A(x:number, y:number)
A(1,2).
A(2,1).
A(2,3).
A(1,4).
A(3,4).
A(4,5).

.decl P(x:number, y:number)
P(x, y) :- A(x, y).   
P(x, y) :- A(x, z), P(z, y).

.output P
